Repository christopherkeim/crypto-real-time-inference, pull requests merged in 2023-10, with the labels that each got.

#26 Kenson/implement fetch
  .gitignore
  README.md
  frontend/.env.local.example
  frontend/app/mock/route.ts
  frontend/components/Prediction/PredictionContainer.tsx
  frontend/components/Prediction/PredictionForm.tsx
  frontend/components/Prediction/PredictionResult.tsx
  frontend/components/PredictionForm.tsx
  frontend/components/hero-home.tsx
Labels: enhancement

#29 Download Models From Model Registry (Prediction Server)
  .gitignore
  Dockerfile
  deploy/__init__.py
  deploy/deploy.sh
  deploy/download_models_from_wandb.py
  deploy/environment.sh.example
  deploy/setup_deploy_deb.sh
  deploy/setup_deploy_ub.sh
  set_environment_variables_template.sh
  src/predict.py
Labels: enhancement

#31 Docker Hub CD Pipeline for Prediction Service
  .github/workflows/push-docker-image-to-docker-hub.yml
  Dockerfile
Labels: enhancement

#33 Dual Chip Docker Hub CD Pipeline (Prediction Service)
  .github/workflows/build-and-push-to-docker-hub.yaml
  .github/workflows/ci.yaml
  Dockerfile
  README.md
Labels: enhancement

#34 Documentation cleanup.
  README.md
  frontend/README.md
Labels: documentation

#36 Continuous Deployment Pipeline for Raspberry Pi (Prediction Service)
  deploy/deploy.sh
  deploy/deploy_container.sh
  deploy/deploy_webhook.sh
  deploy/environment.sh.example
  deploy/go.mod
  deploy/go.sum
  deploy/prediction-docker-compose.yml
  deploy/setup_deploy_deb.sh
  deploy/webhook.go
  pyproject.toml
Labels: enhancement

#37 Improved link handling for badges
  README.md
Labels: documentation

#38 Kenson/policy page
  frontend/app/policy/page.tsx
  frontend/components/ui/FadeAnimation.tsx
Labels: enhancement

#40 Integration for Multiple Cryptocurrency Workflows (Bitcoin & Ethereum)
  Dockerfile
  README.md
  deploy/download_models_from_wandb.py
  graphs/BTC-USD_cnn_loss_curve.jpeg
  graphs/BTC-USD_cnn_test_predictions.jpeg
  graphs/BTC-USD_cnn_validation_predictions.jpeg
  graphs/BTC-USD_lasso_test_predictions.jpeg
  graphs/BTC-USD_lasso_validation_predictions.jpeg
  graphs/ETH-USD_cnn_loss_curve.jpeg
  graphs/ETH-USD_cnn_test_predictions.jpeg
  graphs/ETH-USD_cnn_validation_predictions.jpeg
  graphs/ETH-USD_lasso_test_predictions.jpeg
  graphs/ETH-USD_lasso_validation_predictions.jpeg
  graphs/cnn_loss_curve.jpeg
  graphs/cnn_test_predictions.jpeg
  graphs/cnn_validation_predictions.jpeg
  graphs/lasso_test_predictions.jpeg
  graphs/lasso_validation_predictions.jpeg
  set_environment_variables.sh.example
  src/feature_pipeline.py
  src/nn_train.py
  src/predict.py
  src/server.py
  src/train.py
Labels: enhancement

#41 Image Timezone Configuration and UTC Fields in PredictionResult
  deploy/prediction-docker-compose.yml
  src/server.py
Labels: technical debt

#42 Add Parity for Deploy Setup Scripts (Debian + Ubuntu)
  deploy/setup_deploy_deb.sh
  deploy/setup_deploy_ub.sh
Labels: enhancement
